export type ImageFormat = 'avif' | 'webp' | 'jpg';

// A picture served from public/ as `${basePath}-${width}.${format}`, generated by
// scripts/generate-images.ts. Static URLs (not bundler hashes) keep the prerendered HTML
// and the hydrated client pointing at the same files. Bump the version in basePath when
// the source image changes.
export type ResponsivePicture = {
  basePath: string;
  widths: readonly number[];
  // Order of preference; the last one is the universal fallback of the <img>.
  formats: readonly ImageFormat[];
  width: number;
  height: number;
};
