import { readFile, writeFile } from 'node:fs/promises';

import { buildDotGrid, encodeLandMask } from '../src/features/korea/utils/land-dots.ts';
import { isOnLand, landPolygons, parseTopology } from './land-mask.ts';

// Run with `pnpm globe` when the grid changes, then commit the generated file: the build
// does not depend on world-atlas. Natural Earth 1:50m land (public domain), via world-atlas.
const SOURCE = new URL('../node_modules/world-atlas/land-50m.json', import.meta.url);
const TARGET = new URL('../src/features/korea/data/land-dots.ts', import.meta.url);

// About 1.6° between dots: the Korean peninsula and Japan read clearly on a globe a few
// hundred pixels wide. Antarctica is left out: the globe never tilts that far south.
const GRID = { rowStep: 1.6, minLatitude: -56, maxLatitude: 83.2 } as const;

// Whether each dot of the grid, in order, falls on land.
async function readLandMask(): Promise<boolean[]> {
  const polygons = landPolygons(parseTopology(await readFile(SOURCE, 'utf8')));
  return buildDotGrid(GRID).map(({ longitude, latitude }) =>
    isOnLand(longitude, latitude, polygons),
  );
}

const LAND = await readLandMask();

await writeFile(
  TARGET,
  `// Generated by scripts/generate-land-dots.ts (pnpm globe) from Natural Earth 1:50m land,
// public domain, via world-atlas. Do not edit: regenerate.
export const LAND_DOTS = {
  rowStep: ${String(GRID.rowStep)},
  minLatitude: ${String(GRID.minLatitude)},
  maxLatitude: ${String(GRID.maxLatitude)},
  count: ${String(LAND.length)},
  mask: '${encodeLandMask(LAND)}',
} as const;
`,
);
process.stdout.write(
  `${String(LAND.filter(Boolean).length)} land dots out of ${String(LAND.length)} → ${TARGET.pathname}\n`,
);
