import { alternateHref } from '../src/config/paths.ts';
import { SITE_ORIGIN, SITE_OWNER, SITE_ROLE } from '../src/config/site.ts';
import { type Locale, LOCALES } from '../src/i18n/locales.ts';

// What crawlers and link previews read in a page's head, written into the prerendered HTML
// (scripts/prerender.ts): the page's absolute address, the same page in each language, and
// the card a shared link shows (ADR 0031).

const OPEN_GRAPH_LOCALES = { fr: 'fr_FR', en: 'en_US' } as const satisfies Record<Locale, string>;

// Generated by scripts/generate-social-card.ts (pnpm social-card), 1200 × 630 as link
// previews expect.
export const SOCIAL_CARD = {
  path: '/images/social-card-v2.jpg',
  width: 1200,
  height: 630,
} as const;

// Title and description come as the rendered page wrote them, already escaped for HTML text
// and attributes: only quotes, legal in text, must still be escaped in an attribute.
function attribute(value: string): string {
  return value.replaceAll('"', '&quot;');
}

function alternateLinks(path: string): string[] {
  return [
    ...LOCALES.map(
      (locale) =>
        `<link rel="alternate" hreflang="${locale}" href="${SITE_ORIGIN}${alternateHref(path, '', locale)}">`,
    ),
    `<link rel="alternate" hreflang="x-default" href="${SITE_ORIGIN}/">`,
  ];
}

export function pageHeadTags({
  path,
  locale,
  title,
  description,
}: {
  path: string;
  locale: Locale;
  title: string;
  description: string;
}): string {
  const url = `${SITE_ORIGIN}${path}`;
  return [
    `<link rel="canonical" href="${url}">`,
    ...alternateLinks(path),
    '<meta property="og:type" content="website">',
    `<meta property="og:site_name" content="${SITE_OWNER}">`,
    `<meta property="og:url" content="${url}">`,
    `<meta property="og:title" content="${attribute(title)}">`,
    `<meta property="og:description" content="${attribute(description)}">`,
    `<meta property="og:locale" content="${OPEN_GRAPH_LOCALES[locale]}">`,
    ...LOCALES.filter((other) => other !== locale).map(
      (other) => `<meta property="og:locale:alternate" content="${OPEN_GRAPH_LOCALES[other]}">`,
    ),
    `<meta property="og:image" content="${SITE_ORIGIN}${SOCIAL_CARD.path}">`,
    `<meta property="og:image:width" content="${String(SOCIAL_CARD.width)}">`,
    `<meta property="og:image:height" content="${String(SOCIAL_CARD.height)}">`,
    `<meta property="og:image:alt" content="${SITE_OWNER}, ${SITE_ROLE.replaceAll('&', '&amp;')}">`,
    '<meta name="twitter:card" content="summary_large_image">',
  ].join('');
}

// The gateway at `/` chooses a language (ADR 0026): crawlers learn both from it.
export function gatewayHeadTags(): string {
  return [`<link rel="canonical" href="${SITE_ORIGIN}/">`, ...alternateLinks('/fr')].join('');
}

export function sitemapXml(pages: readonly { path: string }[]): string {
  const urls = pages.map(({ path }) => {
    const alternates = LOCALES.map(
      (locale) =>
        `<xhtml:link rel="alternate" hreflang="${locale}" href="${SITE_ORIGIN}${alternateHref(path, '', locale)}"/>`,
    ).join('');
    return `<url><loc>${SITE_ORIGIN}${path}</loc>${alternates}</url>`;
  });
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${urls.join('')}</urlset>\n`;
}

export function robotsTxt(): string {
  return `User-agent: *\nAllow: /\n\nSitemap: ${SITE_ORIGIN}/sitemap.xml\n`;
}
